{{- if and .Values.postgresdb.enabled .Values.postgresdb.postgresdb_service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "madhava.postgresdb.fullname" . }}-headless
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "madhava.postgresdb.labels" . | nindent 4 }}
  {{- if .Values.podAnnotations }}
  annotations:      
    {{- with .Values.podAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-postgresql
      port: 10040
      targetPort: 10040
  selector:
    {{- include "madhava.postgresdb.selectorLabels" . | nindent 4 }}
{{- end }} 
