apiVersion: v1
kind: Service
metadata:
  name: {{ include "shyama.fullname" . }}-headless
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "shyama.labels" . | nindent 4 }}
  {{- if .Values.podAnnotations }}
  annotations:      
    {{- with .Values.podAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-shyama
      port: {{ .Values.shyama_config.service.port }}
      targetPort: tcp-shyama
  selector:
    {{- include "shyama.selectorLabels" . | nindent 4 }}
