apiVersion: v1
kind: Service
metadata:
  name: {{ include "madhava.fullname" . }}-headless
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "madhava.labels" . | nindent 4 }}
  {{- if .Values.podAnnotations }}
  annotations:      
    {{- with .Values.podAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-madhava
      port: {{ .Values.madhava_config.service.port }}
      targetPort: tcp-madhava
  selector:
    {{- include "madhava.selectorLabels" . | nindent 4 }}
