apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "partha.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "partha.labels" . | nindent 4 }}
data:
  partha_main.json: |-
    {{- mustToPrettyJson .Values.partha_config }}
