{{- if .Values.podSecurityPolicy }}
{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "partha.fullname" . }}
  labels:
    {{- include "partha.labels" . | nindent 4 }}
spec:
  privileged: true
  allowPrivilegeEscalation: true
  fsGroup:
    rule: RunAsAny
  hostNetwork: true
  hostPID: true
  hostPorts:
  - max: 65535
    min: 0
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  readOnlyRootFilesystem: true
  volumes:
    - '*'
{{- end }}
{{- end }}
