apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shyama.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "shyama.labels" . | nindent 4 }}
{{- with .Values.podAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
type: Opaque
data:
  {{- if .Values.shyama_config.shyama_secret }}
  CFG_SHYAMA_SECRET: {{ .Values.shyama_config.shyama_secret | b64enc | quote }}
  {{- else }}
  CFG_SHYAMA_SECRET: {{ printf "%s-secret" .Release.Name | b64enc | quote -}}
  {{- end }}

