apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alertaction.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "alertaction.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "alertaction.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.updateStrategy }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "alertaction.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:          
      {{- if .Values.serviceAccount.create }}
      serviceAccount: "gyeeta-alertaction"
      {{- else }}
      serviceAccount: "default"
      {{- end }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      {{- if .Values.hostAliases }}
      hostAliases: {{- include "alertaction.tplvalues" (dict "value" .Values.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- include "alertaction.tplvalues" (dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "alertaction.affinities.pods" (dict "type" .Values.podAffinityPreset "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "alertaction.affinities.pods" (dict "type" .Values.podAntiAffinityPreset "context" $) | nindent 10 }}
        nodeAffinity: {{- include "alertaction.affinities.nodes" (dict "type" .Values.nodeAffinityPreset.type "key" .Values.nodeAffinityPreset.key "values" .Values.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "alertaction.tplvalues" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "alertaction.tplvalues" (dict "value" .Values.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "alertaction.tplvalues" (dict "value" .Values.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.podPriorityClassName }}
      priorityClassName: {{ .Values.podPriorityClassName }}
      {{- end }}
      securityContext:
        fsGroup: 1001
      containers:
        - name: alertaction
          image: {{ include "alertaction.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            readOnlyRootFilesystem: true 
          args:
            - start
            {{- with .Values.extra.args }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: CFG_SHYAMA_HOSTS
              value: {{ mustToJson .Values.alertaction_config.shyama_hosts | quote }}
            - name: CFG_SHYAMA_PORTS
              value: {{ mustToJson .Values.alertaction_config.shyama_ports | quote }}
          {{- range $key, $value := .Values.extra.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
          {{- end }}
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.lifecycleHooks }}
          lifecycle: {{- include "alertaction.tplvalues" (dict "value" .Values.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- with .Values.mounts.volumeMounts }}
             {{- toYaml . | nindent 10 }}
          {{- end }}              
      volumes:
        {{- with .Values.mounts.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}

