
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "shyama.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "shyama.labels" . | nindent 4 }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
  {{- if .Values.serviceAccount.annotations }}
    {{- include "shyama.tplvalues" ( dict "value" .Values.serviceAccount.annotations "context" $ ) | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
