apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresdb.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "postgresdb.labels" . | nindent 4 }}
{{- with .Values.podAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
type: Opaque
data:
  {{- if .Values.postgresdb_config.password }}
  CFG_POSTGRES_PASSWORD: {{ .Values.postgresdb_config.password | b64enc | quote }}
  {{- else }}
  CFG_POSTGRES_PASSWORD: {{ printf "%s-password" .Release.Name | b64enc | quote -}}
  {{- end }}

