apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresdb.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "postgresdb.labels" . | nindent 4 }}
  {{- if .Values.podAnnotations }}
  annotations:      
    {{- with .Values.podAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-postgresql
      port: {{ .Values.postgresdb_config.port }}
      targetPort: tcp-postgresql
  selector:
    matchLabels:
      {{- include "postgresdb.selectorLabels" . | nindent 6 }}
